name: Ruby Pipeline

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  Build_and_test:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby-version: ['2.7.4']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Compile webpacker
      run: |
        bundle exec rails yarn:install

    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rake db:migrate
        bundle exec rake
